# Generated by Django 3.0.6 on 2020-05-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usersearchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchhistory',
            name='visited',
            field=models.DateField(auto_now=True),
        ),
    ]
